<a href="https://colab.research.google.com/github/droyktton/ICNPG/blob/master/Clases/Clases_rapids/Clases_cudf/ICNPG_CUDF_covidArgentina.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# This get the RAPIDS-Colab install files and test check your GPU.  Run this and the next cell only.
# Please read the output of this cell.  If your Colab Instance is not RAPIDS compatible, it will warn you and give you remediation steps.
!git clone https://github.com/rapidsai/rapidsai-csp-utils.git
!python rapidsai-csp-utils/colab/pip-install.py

In [2]:
import cudf
cudf.__version__

'26.02.01'

## CUDF

In [6]:
%%bash

rm -rf ICNPG
git clone https://github.com/droyktton/ICNPG.git
cp /content/ICNPG/Clases/Clases_rapids/Clases_cudf/reducido.csv Covid19Casos.csv

Cloning into 'ICNPG'...

In [7]:
import cudf

# read CSV from memory
cuda_df = cudf.read_csv('/content/Covid19Casos.csv')

veamos los encabezados

In [8]:

cuda_df.head()

,id_evento_caso,sexo,edad,edad_años_meses,residencia_pais_nombre,residencia_provincia_nombre,residencia_departamento_nombre,carga_provincia_nombre,fecha_inicio_sintomas,fecha_apertura,...,fecha_fallecimiento,asistencia_respiratoria_mecanica,carga_provincia_id,origen_financiamiento,clasificacion,clasificacion_resumen,residencia_provincia_id,fecha_diagnostico,residencia_departamento_id,ultima_actualizacion
0,1000000,M,54,Años,Argentina,CABA,SIN ESPECIFICAR,Buenos Aires,<NA>,2020-06-01,...,<NA>,NO,06,Privado,Caso Descartado,Descartado,02,2020-06-09,0,2021-05-19
1,10000000,F,52,Años,Argentina,CABA,SIN ESPECIFICAR,CABA,<NA>,2021-04-08,...,<NA>,NO,02,Público,Caso Descartado,Descartado,02,2021-04-08,0,2021-05-19
2,10000001,F,22,Años,Argentina,Buenos Aires,Lomas de Zamora,Buenos Aires,2021-04-05,2021-04-08,...,<NA>,NO,06,Público,Caso Descartado,Descartado,06,2021-04-08,490,2021-05-19
3,10000002,F,43,Años,Argentina,Buenos Aires,La Matanza,CABA,<NA>,2021-04-08,...,<NA>,NO,02,Público,Caso Descartado,Descartado,06,2021-04-06,427,2021-05-19
4,10000003,F,33,Años,Argentina,CABA,COMUNA 01,CABA,<NA>,2021-04-08,...,<NA>,NO,02,Público,Caso Descartado,Descartado,02,2021-04-08,001,2021-05-19

selecciono columnas

In [9]:
cuda_df[['sexo','edad','carga_provincia_nombre']]

    sexo edad carga_provincia_nombre
0      M   54           Buenos Aires
1      F   52                   CABA
2      F   22           Buenos Aires
3      F   43                   CABA
4      F   33                   CABA
..   ...  ...                    ...
994    M   64             Santa Cruz
995    F   45                   CABA
996    F   55                   CABA
997    F   59                Córdoba
998    F    9           Buenos Aires

[999 rows x 3 columns]

un nuevo data frame filtrando con condiciones, porteños menores de 35

In [10]:
cuda_df['edad'] = cudf.to_numeric(cuda_df['edad'], errors='coerce')
caba = cuda_df[(cuda_df["residencia_provincia_nombre"] == 'CABA') & (cuda_df["edad"] < 35)]

check a ver si funciona

In [11]:
caba.head()

,id_evento_caso,sexo,edad,edad_años_meses,residencia_pais_nombre,residencia_provincia_nombre,residencia_departamento_nombre,carga_provincia_nombre,fecha_inicio_sintomas,fecha_apertura,...,fecha_fallecimiento,asistencia_respiratoria_mecanica,carga_provincia_id,origen_financiamiento,clasificacion,clasificacion_resumen,residencia_provincia_id,fecha_diagnostico,residencia_departamento_id,ultima_actualizacion
4,10000003,F,33,Años,Argentina,CABA,COMUNA 01,CABA,<NA>,2021-04-08,...,<NA>,NO,02,Público,Caso Descartado,Descartado,02,2021-04-08,001,2021-05-19
5,10000004,F,32,Años,Argentina,CABA,COMUNA 08,CABA,<NA>,2021-04-08,...,<NA>,NO,02,Público,Caso Descartado,Descartado,02,2021-04-06,008,2021-05-19
19,10000018,M,33,Años,Argentina,CABA,COMUNA 02,CABA,<NA>,2021-04-08,...,<NA>,NO,02,Público,Caso Descartado,Descartado,02,2021-04-06,002,2021-05-19
21,10000020,M,22,Años,Argentina,CABA,SIN ESPECIFICAR,CABA,<NA>,2021-04-08,...,<NA>,NO,02,Público,Caso Descartado,Descartado,02,2021-04-06,0,2021-05-19
32,10000030,M,15,Años,Argentina,CABA,SIN ESPECIFICAR,CABA,<NA>,2021-04-08,...,<NA>,NO,02,Público,Caso Descartado,Descartado,02,2021-04-06,0,2021-05-19

In [12]:
male_20_30 = cuda_df[(cuda_df['sexo'] == 'M') & (cuda_df['edad'] >= 20) & (cuda_df['edad'] <= 30)]
print(f"Number of male cases between 20 and 30 years old: {len(male_20_30)}")

Number of male cases between 20 and 30 years old: 119